name: Code quality check

on: [pull_request]

env:
  OUTPUT: Empty

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup init_script
      shell: bash
      run: |
        echo "#!/bin/bash
        root_dir=\${1}
        build_dir=\${2}
        pip install conan
        conan profile detect
        conan install \$root_dir --install-folder=build --build=missing --settings=build_type=Release -c tools.system.package_manager:mode=install
        wget https://sdk.lunarg.com/sdk/download/1.2.170.0/linux/vulkansdk-linux-x86_64-1.2.170.0.tar.gz
        tar xf vulkansdk-linux-x86_64-1.2.170.0.tar.gz -C \$root_dir/lib
        source \$root_dir/lib/1.2.170.0/setup-env.sh" > init_script.sh

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: dependencies
        init_script: init_script.sh
        apt_pckgs: xorg-dev python3-pip
        verbose: true
        cppcheck_args: |
            --enable=all --suppress=functionStatic --suppress=unusedFunction --inline-suppr --inconclusive