name: Code quality check

on: [pull_request]

env:
  OUTPUT: Empty

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup init_script
      shell: bash
      run: |
        echo "#!/bin/bash
        wget https://sdk.lunarg.com/sdk/download/1.3.216.0/linux/vulkansdk-linux-x86_64-1.3.216.0.tar.gz
        tar xf vulkansdk-linux-x86_64-1.3.216.0.tar.gz
        source ./1.3.216.0/setup-env.sh" > init_script.sh

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: dependencies
        apt_pckgs: xorg-dev
        verbose: true
        cppcheck_args: |
            --enable=all --suppress=functionStatic --suppress=unusedFunction --inline-suppr --inconclusive
