name: Code quality check

on: [pull_request]

env:
  OUTPUT: Empty

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup init_script
      shell: bash
      run: |
        cat <<'EOF' > init_script.sh
        #!/bin/bash
        set -euo pipefail

        root_dir=${1}
        build_dir=${2}
        sdk_version=$(wget -qO- https://vulkan.lunarg.com/sdk/latest/linux.txt)

        pip install conan --break-system-packages
        conan profile detect
        conan install "$root_dir" --output-folder="$build_dir" --build=missing --settings=build_type=Release -c tools.system.package_manager:mode=install
        mkdir -p "$root_dir/vulkan"
        wget "https://sdk.lunarg.com/sdk/download/${sdk_version}/linux/vulkan_sdk.tar.xz" -O vulkan_sdk.tar.xz
        tar xf vulkan_sdk.tar.xz -C "$root_dir/vulkan"
        source "$root_dir/vulkan/${sdk_version}/setup-env.sh"
        EOF

        chmod +x init_script.sh

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        cmake_args: -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        exclude_dir: vulkan
        init_script: init_script.sh
        apt_pckgs: xorg-dev python3-pip
        verbose: true
        clang_tidy_args: |
            -extra-arg=-std=c++20
        cppcheck_args: |
            --enable=all --suppress=missingIncludeSystem --suppress=functionStatic --suppress=unusedFunction --inline-suppr --inconclusive --check-level=exhaustive
