name: Windows

on:
  push:
    branches:
      - master
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v1
      with:
        path: "C:\\VulkanSDK\\1.3.216.0"
        key: vulkan-sdk-1.3.216.0

    - name: Setup Vulkan
      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.216.0/windows/VulkanSDK-1.3.216.0-Installer.exe" -OutFile VulkanSDK.exe;
        $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        export VULKAN_SDK="C:\\VulkanSDK\\1.3.216.0"

        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DASSIMP_BUILD_TESTS=0\
           -DASSIMP_BUILD_ASSIMP_TOOLS=0 -DBUILD_SHARED_LIBS=0

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE > output.txt
        cat output.txt

    - name: Post PR comment for warnings/errors
      if: github.ref != 'refs/heads/master'
      uses: JacobDomagala/CompileResultAction@master
      with:
        compile_result_file: ${{runner.workspace}}/build/output.txt
        comment_title: WINDOWS COMPILE RESULT
        compiler: MSVC
        exclude_dir: ${{github.workspace}}/dependencies
