name: Windows

on: [pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DASSIMP_BUILD_TESTS=0\
           -DASSIMP_BUILD_ASSIMP_TOOLS=0 -DBUILD_SHARED_LIBS=0

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE > output.txt
        cat output.txt

    - name: Post PR comment for warnings/errors
      if: ${{ always() }}
      uses: JacobDomagala/CompileResultAction@master
      with:
        compile_result_file: ${{runner.workspace}}/build/output.txt
        comment_title: WINDOWS COMPILE RESULT
        compiler: MSVC
        exclude_dir: ${{github.workspace}}/dependencies
